from .advection_1d import solve_advection_1d
from .advection_2d import solve_advection_2d
from .convection_1d import solve_convection_1d
from .convection_2d import solve_convection_2d
from .diffusion_1d import solve_diffusion_1d
from .diffusion_2d import solve_diffusion_2d
from .burgers_equation_1d import solve_burgers_equation_1d
from .burgers_equation_2d import solve_burgers_equation_2d
from .laplace_2d import solve_laplace_2d
from .poisson_2d import solve_poisson_2d
from .cavity_flow import solve_cavity_flow